name: pybraw
dependencies:
  - conda-forge::pip=22.0.4
  - conda-forge::python=3.7.12
  - conda-forge::numpy=1.21.5
  - conda-forge::pillow=9.0.1
  - conda-forge::termcolor=1.1.0
  - conda-forge::pytest=7.1.1
  - conda-forge::pytest-lazy-fixture=0.6.3
  - conda-forge::pytorch=1.9.1=cuda112py37h3bec1eb_3
  - conda-forge::cudatoolkit=11.2.2
  - conda-forge::gxx=11.2.0
  - conda-forge::gxx_linux-64=11.2.0
  - conda-forge::pybind11=2.9.2
  - conda-forge:libcxx=13.0.1
  - conda-forge::libcxxabi==13.0.1
