name: pybraw
dependencies:
  - pip=21.2.2
  - python=3.7.6
  - pybind11=2.7.0
  - numpy=1.20.3
  - pillow=8.3.1
  - termcolor=1.1.0
  - pytest=6.2.4
  - conda-forge::pytest-lazy-fixture=0.6.3
  - pytorch::pytorch=1.9.0
  - nvidia::cudatoolkit=11.1
